### ISSUE TITLE
Updates to Knowledge graph and Entities

### ISSUE THREAD

**Issue by bramamoorthy** [ambiverse-nlu/ambiverse-nlu#16]
Thanks for providing this rich and seamless framework. 
I have the following questions or need help sort of things. Any information is greatly appreciated. 
1. I wanted to know how frequently [Cadence of] the database/datasets from wikitdata being pulled into Ambiverse.
2. Is there a methodological automated way of upgrading from v18 to v19 if i am currently on v18 dataset of Knowledgegraph and Entities.
3. If i am pushing changesets of ttl/quads from wikidata , would the entity recognition be impacted or not.

**Comment by hoffart** [comment]
Thanks for the positive feedback!

Regarding your questions:
1. We do not have a regular schedule, however we provide the tools to create the database yourself, see https://github.com/ambiverse-nlu/ambiverse-nlu#building-your-own-yago-knowledge-graph (we need to improve our documentation here ...)
2. The version suffix (v18) determines the expected database schema, and only changes in case the database layout change, which should happen only infrequently. The way to upgrade would be to rebuild the database with the current codebase.
3. The kg-backend and entity model (Postgres/Cassandra) should stay in sync, otherwise the entity linking (recognition and disambiguation) might produce identifiers that are not present in the KG. The only way to stay in sync is to rebuild the full database/knowledge graph from scratch.
