### ISSUE TITLE
Results for "Kellogg's" point to wrong Wikidata entity

### ISSUE THREAD

**Issue by mventimi** [ambiverse-nlu/ambiverse-nlu#20]
When we run the following request through AmbiverseNLU:

`curl --request POST --url http://localhost:8080/entitylinking/analyze --header 'accept: application/json' --header 'content-type: application/json' --data $'{"docId": "doc1", "text": "Kellogg\'s is an American multinational food manufacturing company headquartered in Battle Creek, Michigan.", "extractConcepts": "true", "language": "en"}'`

we obtain the following results:
```
{
  "docId": "doc1",
  "language": "en",
  "matches": [
    {
      "charLength": 7,
      "charOffset": 0,
      "text": "Kellogg",
      "entity": {
        "id": "http://www.wikidata.org/entity/Q856886",
        "confidence": 0.21240166844575648
      }
    },
    {
      "charLength": 12,
      "charOffset": 83,
      "text": "Battle Creek",
      "entity": {
        "id": "http://www.wikidata.org/entity/Q810998",
        "confidence": 0.41914338870940004
      }
    },
    {
      "charLength": 8,
      "charOffset": 97,
      "text": "Michigan",
      "entity": {
        "id": "http://www.wikidata.org/entity/Q1166",
        "confidence": 0.31163620702219674
      }
    },
    {
      "charLength": 4,
      "charOffset": 39,
      "text": "food",
      "entity": {
        "id": "http://www.wikidata.org/entity/Q2095",
        "confidence": 0.5883575301498092
      }
    },
    {
      "charLength": 21,
      "charOffset": 44,
      "text": "manufacturing company",
      "entity": {
        "id": "http://www.wikidata.org/entity/Q187939",
        "confidence": 1.0
      }
    }
  ],
  "entities": [
    {
      "id": "http://www.wikidata.org/entity/Q810998",
      "name": "Battle Creek, Michigan",
      "url": "http://en.wikipedia.org/wiki/Battle%20Creek%2C%20Michigan",
      "type": "LOCATION",
      "salience": 0.2317468977580788
    },
    {
      "id": "http://www.wikidata.org/entity/Q856886",
      "name": "Kellogg's",
      "url": "http://en.wikipedia.org/wiki/Kellogg%27s",
      "type": "ORGANIZATION",
      "salience": 0.7863166812635995
    },
    {
      "id": "http://www.wikidata.org/entity/Q2095",
      "name": "Food",
      "url": "http://en.wikipedia.org/wiki/Food",
      "type": "CONCEPT",
      "salience": 0.0
    },
    {
      "id": "http://www.wikidata.org/entity/Q187939",
      "name": "Manufacturing",
      "url": "http://en.wikipedia.org/wiki/Manufacturing",
      "type": "CONCEPT",
      "salience": 0.0
    },
    {
      "id": "http://www.wikidata.org/entity/Q1166",
      "name": "Michigan",
      "url": "http://en.wikipedia.org/wiki/Michigan",
      "type": "LOCATION",
      "salience": 0.22656730944062733
    }
  ]
}
```

In the above result, the entity ID for "Kellogg's" is incorrect. It refers to the Wikidata entity [Q856886](http://www.wikidata.org/entity/Q856886), which is the entity representing a Wikipedia disambiguation page. It should actually refer to [Q856897](https://www.wikidata.org/wiki/Q856897). We see the same issue on our local installation and on the web demo at https://ambiversenlu.mpi-inf.mpg.de.

One additional data point--we did try running this using both "Kellogg" and "Kelloggs" in addition to "Kellogg's". The results are the same in all three cases.

**Comment by hoffart** [comment]
Thx for the report, we will have a look.

It's not a perfect system, though, mistakes like this can and will always happen :)

**Comment by flackbash** [comment]
I had a look at the database and it seems that the mapping from an entity to its Wikidata QID - although most of the times correct - is in some cases weirdly far off, even for prominent entities.

For example, the QID for *"The Lord of the Rings: The Fellowship of the Ring"* ([Q127367](https://www.wikidata.org/wiki/Q127367)) is linked to the Wikipedia article of [Bahadur Shah Zafar](https://en.wikipedia.org/wiki/Bahadur_Shah_Zafar).
The entity "Tripoli" is linked to the QID for *"Category:Eurovision Song Contest entrants for Russia"* ([Q3575](https://www.wikidata.org/wiki/Q3575))
The entity "Africa" is linked to the QID for *"Category:February 1994 events in Asia"* ([Q47464459](https://www.wikidata.org/wiki/Q47464459)).

The following query illustrates this:
```
SELECT entity, humanreadablererpresentation, wikidataid FROM entity_metadata WHERE wikidataid = 'Q3575'
UNION
SELECT entity, humanreadablererpresentation, wikidataid FROM entity_metadata WHERE wikidataid = 'Q127367'
UNION
SELECT entity, humanreadablererpresentation, wikidataid FROM entity_metadata WHERE wikidataid = 'Q47464459'
UNION
SELECT entity, humanreadablererpresentation, wikidataid FROM entity_metadata WHERE wikidataid = 'Q856886'
ORDER BY entity

97625	"Tripoli"	"Q3575"
102142	"Africa"	"Q47464459"
108723	"Kellogg's"	"Q856886"
899780	"Bahadur Shah Zafar"	"Q127367"
```

Do you have any intuition why these problems occur? Is it a problem with Yago? I've been playing around with Yago a little bit but could not identify the same problem there (although that might be due to my lack of expertise).
Where does the mapping to a QID come from?
It would be great to have some insights on this.

And thank you for making the code for this system public!
